variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - build
  - test
  - publish_local
  - trigger_downstream

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - "java --version"
  - "gradle -v"

build_gradle:
  stage: build
  tags:
    - generating_backend
  script:
    - "gradle generateFdl"
# Temporarily disabled, only needed for the test stage
# artifacts:
#   paths:
#     - build
#     - .gradle
#   expire_in: 1 hour

#test_gradle:
#  stage: test
#  tags:
#    - generating_backend
#  script:
#    - "gradle testReport"

publish_local:
  stage: publish_local
  only:
    - deploy_maven_buildserver
  tags:
    - generating_backend
  script:
    - "gradle publishToMavenLocal"
